# Generated by Django 2.2 on 2020-05-31 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=20)),
                ('last_name', models.CharField(blank=True, default='', max_length=20)),
                ('full_name', models.CharField(blank=True, default='', max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, default=0)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('city', models.CharField(blank=True, default='', max_length=25)),
                ('state', models.CharField(blank=True, default='', max_length=25)),
                ('country', models.CharField(blank=True, default='', max_length=25)),
                ('pincode', models.BigIntegerField(blank=True, default=0)),
                ('contact_number', models.BigIntegerField(blank=True, default=0)),
                ('is_married', models.BooleanField(default=0)),
                ('profile_image', models.ImageField(blank=True, default='', upload_to='profile_image/')),
                ('document', models.FileField(blank=True, null=True, upload_to='document/')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
