# Generated by Django 2.2 on 2020-06-18 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mykart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('area', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=200)),
                ('pin_code', models.BigIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=20)),
                ('price', models.PositiveIntegerField(blank=True, default=0)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('discount', models.PositiveIntegerField(blank=True, default=0)),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mykart.Manufacture')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mykart.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_company_name', models.CharField(blank=True, default='', max_length=200)),
                ('seller_name', models.CharField(blank=True, default='', max_length=200)),
                ('area', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=200)),
                ('pin_code', models.BigIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='pincode',
            new_name='pin_code',
        ),
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchase', models.PositiveIntegerField(blank=True, default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mykart.UserDetail')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mykart.ProductDetail')),
            ],
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product_seller',
            field=models.ManyToManyField(blank=True, to='mykart.Seller'),
        ),
        migrations.CreateModel(
            name='AddToKart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.PositiveIntegerField(blank=True, default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mykart.ProductDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mykart.UserDetail')),
            ],
        ),
    ]
