# Generated by Django 2.2 on 2020-06-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykart', '0002_auto_20200619_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='product_image',
            field=models.ImageField(blank=True, default='', upload_to='product_image/'),
        ),
    ]
