# Generated by Django 2.2 on 2020-06-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykart', '0003_productdetail_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_company_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
