# Generated by Django 2.2 on 2020-07-05 12:17

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mykart', '0005_auto_20200705_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='product_image'),
        ),
    ]
